package userinterface;

import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.PrintStream;
import java.util.Observable;
import java.util.logging.Level;
import java.util.logging.Logger;
import kandisimulaatiojava.LyapunovExpSolver;
import kandisimulaatiojava.Phys;
import kandisimulaatiojava.Simulation;

public class MainGui extends javax.swing.JFrame implements UserInterface{

    private Simulation simulation1;
    private Simulation simulation2;
    private LyapunovExpSolver lecalc;
    private long lastUpdateTime = System.currentTimeMillis();
    private FileOutputStream fos;
    private PrintStream fileOut;

    
    public MainGui() {
        initComponents();
        this.setLocationRelativeTo(null);
        simulation1 = new Simulation();
        DrawArea.simulation1 = simulation1;
        simulation2 = new Simulation();
        DrawArea.simulation2 = simulation2;
        
        try {
            fos = new FileOutputStream(new File("tulokset2.txt"));
            fileOut = new PrintStream(fos);
        } catch (IOException ex) {
            Logger.getLogger(LyapunovExpSolver.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        this.setVisible(true);
        startLyaExpSolver();
        
        drawArea.paintImmediately(jPanel1.getBounds());
        labelNValue.setText("");
        labelSeedValue.setText("");
        labelTimeValue.setText("");
        labelTimestepValue.setText("");
        labelTempValue.setText("");
        labelEnergyValue.setText("");
        labelN5.setToolTipText("Mean kinetic energy per atom");
        labelLyaExpValue.setText("");
        
        this.repaint();
    }

    public void startLyaExpSolver() {
        lecalc = new LyapunovExpSolver(simulation1, simulation2);
        lecalc.addObserver(this);
        Thread simThread = new Thread(lecalc);
        simThread.start();
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        pauseButton = new javax.swing.JButton();
        labelN = new javax.swing.JLabel();
        labelNValue = new javax.swing.JLabel();
        labelN1 = new javax.swing.JLabel();
        labelSeedValue = new javax.swing.JLabel();
        labelN2 = new javax.swing.JLabel();
        labelTimeValue = new javax.swing.JLabel();
        labelN3 = new javax.swing.JLabel();
        labelTimestepValue = new javax.swing.JLabel();
        labelN4 = new javax.swing.JLabel();
        labelTempValue = new javax.swing.JLabel();
        labelN5 = new javax.swing.JLabel();
        labelEnergyValue = new javax.swing.JLabel();
        labelN6 = new javax.swing.JLabel();
        labelLyaExpValue = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel3.setMaximumSize(new java.awt.Dimension(850, 850));
        jPanel3.setMinimumSize(new java.awt.Dimension(850, 850));
        jPanel3.setPreferredSize(new java.awt.Dimension(850, 850));

        jPanel1.setMaximumSize(new java.awt.Dimension(800, 800));
        jPanel1.setMinimumSize(new java.awt.Dimension(800, 800));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 800));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        drawArea = new DrawArea();
        drawArea.setSize(800, 800);
        drawArea.setLocation(0,0);
        jPanel1.add(drawArea);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        pauseButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        pauseButton.setText("Start");
        pauseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pauseButtonActionPerformed(evt);
            }
        });

        labelN.setText("Number of atoms:");

        labelNValue.setText("jLabel1");
        labelNValue.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        labelN1.setText("Seed:");

        labelSeedValue.setText("jLabel1");
        labelSeedValue.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        labelN2.setText("Elapsed time (ps):");

        labelTimeValue.setText("jLabel1");
        labelTimeValue.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        labelN3.setText("Time step (fs):");

        labelTimestepValue.setText("jLabel1");
        labelTimestepValue.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        labelN4.setText("Temperature (K):");

        labelTempValue.setText("jLabel1");
        labelTempValue.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        labelN5.setText("<E_kin> (meV):");

        labelEnergyValue.setText("jLabel1");
        labelEnergyValue.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        labelN6.setText("LyaExp (1/ns)");

        labelLyaExpValue.setText("jLabel1");
        labelLyaExpValue.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pauseButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                    .addComponent(labelN2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                    .addComponent(labelN3, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                    .addComponent(labelN4, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                    .addComponent(labelN5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(labelN1, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                        .addGap(44, 44, 44))
                    .addComponent(labelN6, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelNValue, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelTimeValue, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelTimestepValue, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelTempValue, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelEnergyValue, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelSeedValue, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelLyaExpValue, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelN)
                .addGap(5, 5, 5)
                .addComponent(labelNValue)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(labelN1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(labelSeedValue)))
                .addGap(45, 45, 45)
                .addComponent(labelN2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelTimeValue)
                .addGap(18, 18, 18)
                .addComponent(labelN3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelTimestepValue)
                .addGap(55, 55, 55)
                .addComponent(labelN4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelTempValue)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelN5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelEnergyValue)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelN6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelLyaExpValue)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pauseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jMenu1.setText("File");

        jMenuItem1.setText("New simulation");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        lecalc.setPaused(true);
        pauseButton.setText("Start");
        NewSimulationDialog sd = new NewSimulationDialog(this, simulation1, simulation2);
        sd.setLocationRelativeTo(this);
        sd.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void pauseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pauseButtonActionPerformed
        if(lecalc.isPaused()){
            lecalc.setPaused(false);
            pauseButton.setText("Pause");
        }
        else{
            fileOut.close();
            lecalc.setPaused(true);
            pauseButton.setText("Start");
        }
    }//GEN-LAST:event_pauseButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new MainGui().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel labelEnergyValue;
    private javax.swing.JLabel labelLyaExpValue;
    private javax.swing.JLabel labelN;
    private javax.swing.JLabel labelN1;
    private javax.swing.JLabel labelN2;
    private javax.swing.JLabel labelN3;
    private javax.swing.JLabel labelN4;
    private javax.swing.JLabel labelN5;
    private javax.swing.JLabel labelN6;
    private javax.swing.JLabel labelNValue;
    private javax.swing.JLabel labelSeedValue;
    private javax.swing.JLabel labelTempValue;
    private javax.swing.JLabel labelTimeValue;
    private javax.swing.JLabel labelTimestepValue;
    private javax.swing.JButton pauseButton;
    // End of variables declaration//GEN-END:variables
    private DrawArea drawArea;
    
    
    @Override
    public void update(Observable o, Object arg) {
        if(System.currentTimeMillis() - lastUpdateTime < 30) return;
        lastUpdateTime = System.currentTimeMillis();
        
        labelNValue.setText(simulation1.getNumberOfAtoms()+"");
        labelSeedValue.setText(simulation1.getSeed()+"");
        labelTimeValue.setText((Math.round(simulation1.getTime()*1e15))/1e3+" ps");
        labelTimestepValue.setText((Math.round(simulation1.getTimeStep()*1e19))/1e4+" fs");
        labelTempValue.setText((Math.round(simulation1.getTemperature()*1e5))/1e5+" K");
        labelEnergyValue.setText((Math.round(1.5* Phys.KB*simulation1.getTemperature()*1e8/ Phys.E_CHARGE))/1e5+" meV");
        labelLyaExpValue.setText((Math.round(lecalc.getLyapunovExp()/1e4))/1e5+" ns^-1");
        
        //fileOut.println(lecalc.getLyapunovExp()+" "+lecalc.getPhaseSpaceDiff());
        //fileOut.flush();

                
        /*jPanel1.paintImmediately(drawArea.getBounds());
        jPanel2.paintImmediately(timeLabel.getBounds());
        jPanel2.paintImmediately(tempLabel.getBounds());*/
        repaint();
                
    }
}
